import { Space, AccessRequest, DashboardStats } from './types';

// 샘플 장소 데이터
export const sampleSpaces: Space[] = [
  {
    id: '1',
    name: '대회의실 A',
    type: 'meeting_room',
    location: '본관 3층',
    capacity: 20,
    description: '프로젝터 및 화상회의 장비 구비',
    requiresApproval: true,
    isActive: true,
  },
  {
    id: '2',
    name: '소회의실 B',
    type: 'meeting_room',
    location: '본관 2층',
    capacity: 8,
    description: '화이트보드 및 모니터 구비',
    requiresApproval: true,
    isActive: true,
  },
  {
    id: '3',
    name: '메인 전시장',
    type: 'exhibition',
    location: '별관 1층',
    capacity: 200,
    description: '대형 전시 및 행사 진행 가능',
    requiresApproval: true,
    isActive: true,
  },
  {
    id: '4',
    name: '컨퍼런스홀',
    type: 'conference',
    location: '본관 5층',
    capacity: 100,
    description: '대규모 발표 및 행사용',
    requiresApproval: true,
    isActive: true,
  },
  {
    id: '5',
    name: '세미나실 C',
    type: 'seminar',
    location: '본관 4층',
    capacity: 30,
    description: '강의 및 세미나 진행',
    requiresApproval: true,
    isActive: false,
  },
];

// 샘플 출입 요청 데이터
export const sampleRequests: AccessRequest[] = [
  {
    id: '1',
    spaceId: '1',
    spaceName: '대회의실 A',
    applicantName: '김민수',
    applicantEmail: 'minsu.kim@company.com',
    applicantDepartment: '개발팀',
    purpose: '주간 팀 회의',
    requestDate: '2026-05-20',
    accessDate: '2026-05-23',
    startTime: '10:00',
    endTime: '12:00',
    attendees: 15,
    status: 'pending',
  },
  {
    id: '2',
    spaceId: '3',
    spaceName: '메인 전시장',
    applicantName: '이지은',
    applicantEmail: 'jieun.lee@company.com',
    applicantDepartment: '마케팅팀',
    purpose: '신제품 런칭 행사',
    requestDate: '2026-05-19',
    accessDate: '2026-05-25',
    startTime: '09:00',
    endTime: '18:00',
    attendees: 150,
    status: 'pending',
  },
  {
    id: '3',
    spaceId: '4',
    spaceName: '컨퍼런스홀',
    applicantName: '박준호',
    applicantEmail: 'junho.park@company.com',
    applicantDepartment: '인사팀',
    purpose: '신입사원 오리엔테이션',
    requestDate: '2026-05-18',
    accessDate: '2026-05-22',
    startTime: '13:00',
    endTime: '17:00',
    attendees: 50,
    status: 'approved',
    reviewedBy: '관리자',
    reviewedAt: '2026-05-19',
  },
  {
    id: '4',
    spaceId: '2',
    spaceName: '소회의실 B',
    applicantName: '최서연',
    applicantEmail: 'seoyeon.choi@company.com',
    applicantDepartment: '디자인팀',
    purpose: 'UI 리뷰 미팅',
    requestDate: '2026-05-17',
    accessDate: '2026-05-21',
    startTime: '14:00',
    endTime: '16:00',
    attendees: 6,
    status: 'approved',
    reviewedBy: '관리자',
    reviewedAt: '2026-05-18',
  },
  {
    id: '5',
    spaceId: '1',
    spaceName: '대회의실 A',
    applicantName: '정현우',
    applicantEmail: 'hyunwoo.jung@company.com',
    applicantDepartment: '영업팀',
    purpose: '고객사 미팅',
    requestDate: '2026-05-16',
    accessDate: '2026-05-20',
    startTime: '15:00',
    endTime: '17:00',
    attendees: 10,
    status: 'rejected',
    reviewedBy: '관리자',
    reviewedAt: '2026-05-17',
    notes: '해당 시간대 다른 예약 존재',
  },
  {
    id: '6',
    spaceId: '3',
    spaceName: '메인 전시장',
    applicantName: '한소희',
    applicantEmail: 'sohee.han@company.com',
    applicantDepartment: '기획팀',
    purpose: '사내 전시회',
    requestDate: '2026-05-21',
    accessDate: '2026-05-28',
    startTime: '10:00',
    endTime: '16:00',
    attendees: 80,
    status: 'pending',
  },
];

// 대시보드 통계 계산
export const calculateStats = (requests: AccessRequest[], spaces: Space[]): DashboardStats => {
  return {
    totalRequests: requests.length,
    pendingRequests: requests.filter(r => r.status === 'pending').length,
    approvedRequests: requests.filter(r => r.status === 'approved').length,
    rejectedRequests: requests.filter(r => r.status === 'rejected').length,
    totalSpaces: spaces.length,
    activeSpaces: spaces.filter(s => s.isActive).length,
  };
};
